### PR TITLE
Syntax fixes

### PR DESCRIPTION
**Pull request by Samplasion**

### CODE REVIEW

**Review by NightScript370 — APPROVED** [review]
This is correct syntax, though this code could use a redesign

**Comment by NightScript370** [comment]
This should be closed

**Comment by Miky88** [comment]
it has conflitcts ._.

**Comment by NightScript370** [comment]
Yes, because it was already committed in a form of a different pull request

**Comment by Miky88** [comment]
alright.. <@280399026749440000> close this :D

**Comment by Samplasion** [comment]
Alright, closed

**Pull request closed without merging**
