### PR TITLE
Catch the error in our logs

### PR DESCRIPTION
**Pull request by Miky88**

### CODE REVIEW

**Comment by Miky88** [comment]
i hate whitespaces... why autocorrect doesn't catch them!?

**Comment by Samplasion** [comment]
I'm not 100% sure that'll fix the errors

**Comment by Miky88** [comment]
no but that should catch error and we can fix it later *after another gnome*

**Comment by Samplasion** [comment]
You know, I'd like to commit the fix all-in-one

**Comment by Miky88** [comment]
*what should we do now?*

**Comment by Miky88** [comment]
~~merge and update, easy~~

**Comment by Miky88** [comment]
Ok, committed and fixed.

**Comment by Samplasion** [comment]
wait
why'd you close it?
we still need to commit it

**Comment by Miky88** [comment]
what... u already committed it :thinking:

**Comment by Samplasion** [comment]
I commited to your branch, not to the bot

**Comment by Miky88** [comment]
if you don't have already committed it... do this now!

**Comment by Samplasion** [comment]
hm fine

**Comment by Miky88** [comment]
> I committed to your branch

ah.

**Review by Samplasion — APPROVED** [review]

**Comment by Miky88** [comment]
click close :)

**Pull request merged**
