### PR TITLE
Added admin level

### PR DESCRIPTION
**Pull request by Miky88**
5 for admin

### CODE REVIEW

**Comment by NightScript370** [comment]
Please explain the point of this

**Comment by Miky88** [comment]
It was for ungban command

**Comment by NightScript370** [comment]
That command doesn't seem to exist though

**Comment by Miky88** [comment]
I know, check in old pull requests.. I tryed to make one

**Comment by Miky88** [comment]
Also this is useless now so, I'm going to close this conversation.

**Pull request closed without merging**
